nameOverride: ""

fullnameOverride: ""

annotations: {}

replicas: 1

strategy:
  type: Recreate
  # rollingUpdate:
  #   maxUnavailable: 1
  #   maxSurge: 2

podLabels: {}

podAnnotations: {}

podSecurityContext: {}
  # runAsUser: 1000
  # runAsGroup: 1000
  # fsGroup: 1000

nodeSelector: {}

affinity: {}

tolerations: []

terminationGracePeriodSeconds: 30

imagePullSecrets: []

grpcPoller:
  image:
    repository: fedora
    tag: latest
    pullPolicy: IfNotPresent

  containerSecurityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  extraEnv: []

  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 2Gi
    # requests:
    #   cpu: 300m
    #   memory: 1Gi

  grpcHost: rpc.mainnet.succinct.xyz:443

  grpcImportPath: /proto

  scriptPath: /script

  outputPath: /data

metricsExporter:
  image:
    repository: telegraf
    tag: 1.35.4-alpine
    pullPolicy: IfNotPresent
    
  containerSecurityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  extraEnv: []

  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 2Gi
    # requests:
    #   cpu: 300m
    #   memory: 1Gi
  
  metricPort: 9273

  outputPath: /data
  
  configPath: /etc/telegraf
  
  config:
    telegraf: |-
      [agent]
        interval = "30s"
        round_interval = true
        flush_interval = "30s"
        omit_hostname = true
        skip_processors_after_aggregators = false
      
      [[outputs.prometheus_client]]
        listen = ":9273"
        path = "/metrics"
        metric_version = 2
        string_as_label = false
        collectors_exclude = ["gocollector", "process"]

service:
  annotations: {}
  type: ClusterIP
  loadBalancerIP: ""
  externalTrafficPolicy: Cluster

serviceMonitor:
  enabled: true
  namespace: ""
  labels: {}
  annotations: {}
  tlsConfig: {}
  scheme: http
  path: /metrics
  interval: 30s
  scrapeTimeout: 30s
