apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "succinct-external-monitoring.fullname" . }}-proto
  labels:
    {{- include "succinct-external-monitoring.labels" . | nindent 4 }}
data:
  types.proto: |-
    {{ .Files.Get "files/proto/succinct-network/proto/types.proto" | nindent 4 }}
  network.proto: |-
    {{ .Files.Get "files/proto/succinct-network/proto/network.proto" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "succinct-external-monitoring.fullname" . }}-script
  labels:
    {{- include "succinct-external-monitoring.labels" . | nindent 4 }}
data:
  polling.py: |-
    {{ .Files.Get "files/script/polling.py" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "succinct-external-monitoring.fullname" . }}-config
  labels:
    {{- include "succinct-external-monitoring.labels" . | nindent 4 }}
data:
  telegraf.conf: |-
    {{ .Values.metricsExporter.config.telegraf | nindent 4 }}
