{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "succinct-external-monitoring.fullname" . }}
  {{- with .Values.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "succinct-external-monitoring.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Values.serviceMonitor.annotations }}
    {{- toYaml .Values.serviceMonitor.annotations | nindent 4 }}
  {{- else }}
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      honorLabels: true
      port: metrics
      path: {{ .Values.serviceMonitor.path }}
      scheme: {{ .Values.serviceMonitor.scheme }}
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  jobLabel: {{ .Release.Name }}
  selector:
    matchLabels:
      {{- include "succinct-external-monitoring.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
